### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by codesardine** [codesardine/Jade-Application-Kit#12]
#### Expected Behavior

after importing AK module calling the main function should open a window
#### Actual Behavior

we get this
AttributeError: 'NoneType' object has no attribute 'endswith' 
#### Possible Fix

maybe moving if statments to a function
#### Steps to Reproduce

from j import AK
AK.main()

**Comment by vmnlopes** [comment]
this is related with closed bug #11
