### ISSUE TITLE
[Feature request] Tag releases

### ISSUE THREAD

**Issue by jonathonf** [codesardine/Jade-Application-Kit#29]
#### Detailed Description
There are currently no releases tagged in the repo. The commit of a release version should be tagged.

#### Context
This is important for packaging and release notification.

It helps packagers and maintainers, as well as anyone who wants to know what the current release version is.

## Possible Implementation

```
$ git tag 0.36
$ git push --tags
```

**Comment by codesardine** [comment]
sure I don't see a problem doing this, but I already have a release here https://github.com/codesardine/Jade-Application-Kit/blob/master/setup.py 

The PKGBUILD pulls version number from there, so do we need this also?

**Comment by jonathonf** [comment]
Yes, absolutely. A PKGBUILD file is Arch-specific, and the version number should be a "known value" rather than something to be extracted from a file.

Have a read of https://semver.org/ for a good versioning scheme.

**Comment by codesardine** [comment]
Ok I will have to read about tags, since am not familiar with it will implement it on next update. :smile:

**Comment by codesardine** [comment]
done  https://github.com/codesardine/Jade-Application-Kit/commit/6bd0b0fde6562acdc6d43bdb44e98a6d04ca00c4

**Comment by jonathonf** [comment]
Are you sure this is ready for version 1.0.0? (e.g. is there API documentation?)

https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase
https://semver.org/#how-do-i-know-when-to-release-100

If it is, you might also want to update the README. :wink:

**Comment by codesardine** [comment]
the api is not changing again, I might add to it but that wont be for now, documentation here will update it later on today https://github.com/codesardine/Jade-Application-Kit/wiki, is being used in production so it might as well be v1.
