### ISSUE TITLE
nonsensical FAQ

### ISSUE THREAD

**Issue by hub229ox** [codesardine/Jade-Application-Kit#37]
> Does this come with a server?
> No it does not come with its own server, Jade Application is serveless, you can use your own server.

let's assume for the sake of argument that this was indeed a legit FAQ, which it is not.

Anyhow, the lines above are non-sensical throwing around of buzzwords since no one the heck knows what kind of server you are even talking about.

The most import legit FAQ is this: 

**How does Jade autostart?** and **how can I get rid of Jade quickly?** since it violates each and every standard of autostarting in a well defined way and lacks any documentation about that important issue.

**LiquidShell**, replacing plasmaShell , does it much more benignly by way of one easy to find autostart entry in KDE.

**Comment by codesardine** [comment]
I think you confusing this repo with https://github.com/codesardine/Jadesktop.

This a framework for building hybrid web/desktop applications, anyone into web app development knows that they need a http server so the front end talks with the back end, it does not autostart you use it as a base for your own application.

For autostart jade-dashboard, all you need to do is create a .desktop file, there is only one standard you can find it here: https://specifications.freedesktop.org/autostart-spec/autostart-spec-0.5.html
