### ISSUE TITLE
MS-OFFICE-ONLINE Can't create new document with office 365.

### ISSUE THREAD

**Issue by leonardosegurat** [codesardine/Jade-Application-Kit#38]
##  BUGS

When using [MS-OFFICE-ONLINE](https://gitlab.manjaro.org/applications/ms-office-online-launcher/tree/master), and logging in with my university's account, it is not possible to create new documents.

#### Context

Creating a new document works with personal and uni account on browser, but only with personal account with JAK trough ms-office-online launcher. Uni account gets [this](https://imgur.com/a/we3SDrJ) error mesage.

#### Expected Behavior

While logged in trough my school's accountl (Office 356);
Clicking on "Create new blank document" creates and opens a new blank document, just like the regular office online.

#### Actual Behavior

Clicking on "Create new blank document, or any other means of creating a document from within Office 365 online yields [this](https://imgur.com/a/we3SDrJ) error mesage.

#### Steps to Reproduce

1. Log in to office online using a microsoft 365 account.
2. Click create new blank document.

#### Your Environment

python-jade-application-kit  1.3.5-2
Pygi version: 
python version: 3.7.2-3
Linux distro: Manjaro stable
Link to ~~your~~ affected project: https://gitlab.manjaro.org/applications/ms-office-online-launcher/tree/master
ms-office-online version: 18.04.4-2

**Comment by codesardine** [comment]
Sorry for the late response, at the moment i don't have a way to test this on 365, anyway i will leave this open until it gets resolved.
