### ISSUE TITLE
Blank page on load

### ISSUE THREAD

**Issue by codesardine** [codesardine/Jade-Application-Kit#51]
something has changed in the way URL requests are processed.

**Comment by Steffan153** [comment]
I noticed this, and a workaround is to remove the `url_rules`.

**Comment by codesardine** [comment]
Removing ```url_rules``` does not work for me but removing ```online=true```,  does

**Comment by Steffan153** [comment]
what happens when online is false? does it get no internet?

**Comment by codesardine** [comment]
disables, cookies/dns-prefetch/cache
