### ISSUE TITLE
Open file prompt ugly

### ISSUE THREAD

**Issue by Steffan153** [codesardine/Jade-Application-Kit#59]
When I use something to open or download a file, a really really ugly file prompt comes up:

<img src="https://i.imgur.com/hETri6E.png">

Basically, the problem is it's all black. Is some high contrast thing on?

**Comment by codesardine** [comment]
That should be a theme issue, what happens if you change the theme?

This is how mine looks like.
![file-dialog](https://user-images.githubusercontent.com/4250006/60039792-7e110a80-96af-11e9-86e1-5ae77d592715.png)

**Comment by Steffan153** [comment]
I guess it's gnome, changing the theme doesn't help. 
<img src="https://i.imgur.com/mRmDWl9.png">

**Comment by Steffan153** [comment]
This works with Office Online actually, just not with my own one (Udemy Online).

**Comment by codesardine** [comment]
read this: https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications

check inside  ~/.config/Trolltech.conf

**Comment by Steffan153** [comment]
Didn't work, sorry. I set it to adwaita

**Comment by codesardine** [comment]
check if you have qt5-styleplugins installed, change to your current theme not adwaita, and restart

**Comment by codesardine** [comment]
Can you post the URL?

**Comment by Steffan153** [comment]
To what?

**Comment by Steffan153** [comment]
Sorry for taking your time, but still didn't help. My gnome shell and applications theme is Mojave-light.

**Comment by Steffan153** [comment]
Url to app is udemy.com I was saving an attachment from a course lecture.

**Comment by Ste74** [comment]
We use kvantum engine for qt style.. check kvantum config app to find one theme to use ...

**Comment by Steffan153** [comment]
Thanks you fixed it!
