### ISSUE TITLE
Web sockets not working with dropbox

### ISSUE THREAD

**Issue by codesardine** [codesardine/Jade-Application-Kit#60]

**Comment by Steffan153** [comment]
aren't these things something for the qt guys to fix?

**Comment by codesardine** [comment]
Not sure, is something I need to test, for cross domains, as I am having connection errors.

**Comment by Steffan153** [comment]
Websockets work for me.

**Comment by codesardine** [comment]
dropbox is giving some error messages, seems to work fine everywhere else.
