### ISSUE TITLE
"'Shiboken.ObjectType' object is not iterable" with Python 3.8

### ISSUE THREAD

**Issue by Brueggus** [codesardine/Jade-Application-Kit#67]
#### Detailed Description
I've updated to Python 3.8 recently. Trying to run the example from the readme, I get the following error:

`TypeError: 'Shiboken.ObjectType' object is not iterable`

#### Steps to Reproduce
Run in Python 3.8:

```
>>> from JAK.Application import JWebApp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/JAK/Application.py", line 12, in <module>
    from JAK.Widgets import JWindow
  File "/usr/lib/python3.8/site-packages/JAK/Widgets.py", line 16, in <module>
    class SystemTrayIcon(QSystemTrayIcon):
TypeError: 'Shiboken.ObjectType' object is not iterable
```

#### Your Environment

python version: 3.8
pyside2: 5.13.2
Linux distro: Arch

**Comment by codesardine** [comment]
Hopefully, it will be solved with PySide 5.14.
https://bugreports.qt.io/browse/PYSIDE-1140
