### ISSUE TITLE
Office365 - Segmentation error

### ISSUE THREAD

**Issue by ilteoood** [codesardine/Jade-Application-Kit#69]
##  BUGS

After I correctly logged in Office365 WebApplication, and after a 3 hours of correct usage, when I retry to open an Office application like PowerPoint, the WebView forcely close after ~3 seconds.

#### Context

Segmentation error (core dump created)

#### Expected Behavior

Not stop working randomly

#### Actual Behavior

Close after ~3 seconds

#### Possible Fix

That's hard to find: can't event debug

#### Steps to Reproduce

1. LogIn in office 365 (I've used a business account)
2. Use every app (Word, PowerPoint)
3. Ramdomly, it starts to crash

#### Context

Reach OneDrive for business

#### Your Environment

jak-cli --url https://www.office.com/launch/powerpoint?auth=2 --title P --dev
JAK v2.1.3
PyQt5 Bindings
Debugging Mode On
NVIDIA detected:Known bug - kernel rejected pushbuf
Falling back to Software Rendering

DevTools listening on ws://127.0.0.1:9000/devtools/browser/b39b9aab-515e-46dd-9fc6-9ea1dc21581d
Engine interprocess communication (IPC) up and running:
Use of deprecated not thread-safe setter, use setUrlRequestInterceptor instead.
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.14.0 Chrome/77.0.3865.129 Safari/537.36
Loading URL:https://www.office.com/launch/powerpoint?auth=2
Registering ['view'] Instance
Engine interprocess communication (IPC) up and running:
URL scheme handler already installed for the scheme: ipc
Use of deprecated not thread-safe setter, use setUrlRequestInterceptor instead.
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.14.0 Chrome/77.0.3865.129 Safari/537.36
Loading URL:http://127.0.0.1:9000
Registering and Retrieving ['win'] Instance
{'view': <JAK.WebEngine.JWebView object at 0x7f643f3c9f70>, 'win': <JAK.Widgets.JWindow object at 0x7f64345433a0>}
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:9000
Document Ready in: 40 seconds
Segmentation error (core dump created)

Pygi version: 1.0.3
python version: 3.8.0
Linux distro: 5.4.2-1-MANJARO
Link to your project: NA

**Comment by codesardine** [comment]
I can't replicate this, What branch are you on?

**Comment by ilteoood** [comment]
I've installed everything from Pacman

**Comment by codesardine** [comment]
I mean are you on Stable, Testing or Unstable?

**Comment by codesardine** [comment]
Seems there are some missing dependency's, that should not cause a core dump. Remove and reinstall the package including python-jade-application-kit, 
Delete the contents on /home/username/.jak make sure you have pyqt5 and python-pyqtwebengine installed, let me know if that works for you.

**Comment by ilteoood** [comment]
The problem persist.
This time I've tried to clean everything, installing the dependencies from the requirements file and the setup from the master branch.

**Comment by codesardine** [comment]
Did you try with pyside2 bindings?

```
export JAK_PREFERRED_BINDING=PySide2
```

**Comment by ilteoood** [comment]
Yes, this is the output:

```
[teo@teo-pc ~]$ export JAK_PREFERRED_BINDING=PySide2
[teo@teo-pc ~]$ jak-cli --url https://www.office.com/launch/word?auth=2 --title Word
JAK v2.1.3
PySide2 Bindings, JAK_PREFERRED_BINDING environment variable not set.
Production Mode On, use (--dev) for debugging
NVIDIA detected:Known bug - kernel rejected pushbuf
Falling back to Software Rendering
Engine interprocess communication (IPC) up and running:
Use of deprecated not thread-safe setter, use setUrlRequestInterceptor instead.
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.14.0 Chrome/77.0.3865.129 Safari/537.36
Loading URL:https://www.office.com/launch/word?auth=2
Registering ['view'] Instance
Registering and Retrieving ['win'] Instance
Segmentation error (core dump created)
```

**Comment by codesardine** [comment]
You have deleted the cache? on
/home/username/.jak

**Comment by ilteoood** [comment]
Yes, before the new installation from master branch
```
[teo@teo-pc ~]$ ~
bash: /home/teo: Is a directory
[teo@teo-pc ~]$ ls -la | grep '.jak'
[teo@teo-pc ~]$ 
```

**Comment by codesardine** [comment]
I going to need some help debugging this since I can't reproduce on my end, could you install gdb
```
pacman -S gdb
```
run gdb
```
gdb
```
Then type
```
(gdb) file python
(gdb) run /usr/bin/ms-office-online
```
And paste the output here, Thanks

**Comment by ilteoood** [comment]
I did a clean installation of manjaro and I can't recreate this problem.
Thank you for your time.
