### ISSUE TITLE
Pyside2 to PySide2 in WebEngine.py

### ISSUE THREAD

**Issue by ydallilar** [codesardine/Jade-Application-Kit#70]
There seems to be a typo in WebEngine.py. I realized this packaging version 2.1.3 for Arch Linux.

Here is the patch:
https://aur.archlinux.org/cgit/aur.git/tree/Pyside_fix.patch?h=jade-application-kit

**Comment by codesardine** [comment]
Thanks - https://github.com/codesardine/Jade-Application-Kit/commit/5745c5d6c8d831df75e96f189db34f1b40047a8c
