### ISSUE TITLE
JAK apps break due to some PyQT error

### ISSUE THREAD

**Issue by abdullah-if** [codesardine/Jade-Application-Kit#74]
JAK packages coredump due to some issue to load plugin
System:
Manjaro Linux 20.0.3
Up-to-date on testing branch as on Sun 07 Jun 2020 07:39:21 UTC

Command:
```whatsapp-web``` 

Desired output:
The JAK app will open a site in a new window.

Output:                                                                          
```JAK v3.5.3
PyQt5 Bindings
No protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-org.kde.kwin.qpa, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

```

**Comment by codesardine** [comment]
You have a issue with shared libs on your local machine, open a post on manjaro forum.

https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found/15

**Comment by abdullah-if** [comment]
Yes, another day, I figured out I can't run any graphical software from cli when this error appeared.

**Comment by codesardine** [comment]
Reinstalling your QT5 libs might fix it.
